### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by dakorpar** [gameeapp/nette-monolog#1]
hey, some more docs on basic configuration options after adding extension?

**Comment by pilec** [comment]
Hello,

thanks for the first issue in this repo! TBH this is for now test project for one of our product (I know, I should tag that better than 1.0.0, and I'm sorry for that) and it's still in the phase of research, so that's the reason, why there is no documentation yet. But don't worry, when we finally figured out how to deal with, I personally write one. ETA 2 months.
